### ISSUE TITLE
Not Getting The Todos List

### ISSUE THREAD

**Issue by vikramadityasen** [ExtremityIndia/ajax-spring-popup#1]
i am not getting the list todos in response as i have entered the url :http://localhost:8091/ajax-spring-popup/pages/index.htm .Please check the screenshot i have attached.
![untitled](https://cloud.githubusercontent.com/assets/10785062/6345002/48a5dadc-bc26-11e4-8c06-638fbf851178.png)

**Comment by pradipshinde** [comment]
change 8080 port no to <b> your tomcat port no 80..  <b> in your index.htm file then try

**Comment by vikramadityasen** [comment]
thanks pradeep it's working now.

**Comment by sumitramteke** [comment]
Guys much appreciate for keeping your enthu in applying new standards of loggin issues
